### ISSUE TITLE
SageAttention CUDA kernel crash — template unusable on RunPod Serverless

### ISSUE THREAD

**Issue by sinaneshat** [wlsdml1114/Infinitetalk_Runpod_hub#15]
Hi there,

I'm using the InfiniteTalk RunPod Serverless template (the only available template for InfiniteTalk on RunPod) and I'm experiencing a critical SageAttention crash that makes the template completely unusable.

Environment:

RunPod Serverless
GPU: H100 SXM (80GB) — Compute Capability 9.0
CUDA: 12.8
The pre-built Docker image from the template (I have no ability to modify the Dockerfile or install/uninstall packages in Serverless mode)
Error:
The workflow fails immediately during sampling with the following error:

```
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
Exception raised from throw_data_ptr_access_error at /pytorch/c10/core/TensorImpl.cpp:307
```
The full traceback points to:

```
sageattention/quant.py, line 172, in per_warp_int8
    _fused.quant_per_warp_int8_cuda(q, q_int8, q_scale, BLKQ, WARPQ, _tensor_layout)
```
What I've tried:

❌ RTX 4090 (24GB, CC 8.9): CUDA error: no kernel image is available for execution on the device (cudaErrorNoKernelImageForDevice)
❌ A6000 / A40 (48GB, CC 8.6): SM90 kernel is not available. Make sure you GPUs with compute capability 9.0.
❌ H100 SXM (80GB, CC 9.0): Cannot access data pointer of Tensor that doesn't have storage
So the image doesn't work on any GPU tier available on RunPod Serverless.

Root Cause:
This appears to be the same known issue reported in [ComfyUI Issue #12053](https://github.com/Comfy-Org/ComfyUI/issues/12053?utm_source=app.chatqt.com), where SageAttention 2.2.0 crashes with InfiniteTalk's WanVideoSampler workflow. The suggested workaround is to use SDPA attention mode instead of SageAttention, or to uninstall/update SageAttention in the Docker image.

Request:
Since this is a Serverless template and I cannot modify the Docker image or run shell commands, could you please:

Update the Docker image to either:
Remove or update SageAttention to a compatible version, OR
Set the default attention mode to sdpa instead of sageattn
Provide a workaround if there's a way to override the attention mode via the API request payload without modifying the image.
The template is currently completely broken for all GPU types on RunPod Serverless. Any fix or guidance would be greatly appreciated.

**Comment by wlsdml1114** [comment]
Hi, thanks for you interest of my project.
which release did you tried? recent blackwell version release is for blackwell series GPU such as 5090, RTX Pro 6000, B100.
and the sage attention for cc 12.0 is built in the image.
so without the black well GPU, it may occur the problem

**Comment by sinaneshat** [comment]
Hi, thanks for the response! I switched to RTX 5090. 
as you suggested, and the SageAttention issue is now resolved.

However, I'm now getting a new error on the latest release:

handler.py, line 316, in handler:
```
    if person_count == "multi":
NameError: name 'person_count' is not defined

```
It seems like the `person_count` variable is not being extracted 
from the job input in the latest version of handler.py, 
even though I'm sending it in the payload:

"person_count": "single"

The older handler.py correctly reads this 
variable around line 295, but the new version seems to 
be missing that extraction before line 316.

**Comment by wlsdml1114** [comment]
yep, i'll gonna fix it soon

**Comment by degoldmedia-tech** [comment]
> yep, i'll gonna fix it soon

any update on that?

**Comment by wlsdml1114** [comment]
You guys can use release version infinitetalk_v2.0_blackwell.
the bug release is for skyreelsV3, i'm on this now
